### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by burdikov** [maybe-hello-world/academic-cv#1]
In modern world, one should be careful with leading teans. It's safer to lead teams.

https://github.com/maybe-hello-world/academic-cv/blob/84d0bb49c225a40820573be26d598736daefe0fb/tex/cv.tex#L118

**Comment by maybe-hello-world** [comment]
Thank you, I'll consider your proposal and adjust my goals. It's time to admit that the world has changed.
Resolved by cada3a7c435e6d80017f879b8d1125008fdbd9c6.
